### ISSUE TITLE
请问大佬能不能分享一下思路

### ISSUE THREAD

**Issue by TGhoul** [liuxiaoyucc/jd-helper#1]
我想实现一下自动抢炸弹的功能，昨天搜了好多资料，发现 httpcanary 可以实现抓包，但是 root 手机设置好证书以后，APP貌似开启了证书校验，显示连接不上网络。

大佬不介意的话，可否分享一下思路？

**Comment by liuxiaoyucc** [comment]
我用的fiddler 4, 设置好移动端就行了, 也没有root手机, 可能是京东不同模块有区别?

**Comment by liuxiaoyucc** [comment]
你这抢炸弹是什么活动, 我没看见入口在哪...

**Comment by TGhoul** [comment]
> 你这抢炸弹是什么活动, 我没看见入口在哪...

在叠蛋糕活动里面，战队比拼有个扔炸弹的按钮，定时扔炸弹
