### ISSUE TITLE
大佬可以加个京东的宠汪汪吗？

### ISSUE THREAD

**Issue by bsZzz** [liuxiaoyucc/jd-helper#10]

**Comment by bsZzz** [comment]
https://raw.githubusercontent.com/yuanxiaowa/seckill-plugin/e14b3c2e16b29244f4cc1ba3ded0dc2d2a42c618/src/background/jd/task/joy.ts

我找到了这个typescript，不知道有没有帮助。

**Comment by liuxiaoyucc** [comment]
简单看了下宠汪汪, 应该可以实现的

**Comment by bsZzz** [comment]
可以自動兌換京豆就好了 用cron 跑

**Comment by bsZzz** [comment]
> 简单看了下宠汪汪, 应该可以实现的


用cron 跑自動兌換京豆就不會搶不到名額了

**Comment by bsZzz** [comment]
> > 简单看了下宠汪汪, 应该可以实现的
> 
> 
> 用cron 跑自動兌換京豆就不會搶不到名額了

還有「種豆得豆」大佬有空也幫忙看看吧😂
