### ISSUE TITLE
sharecode怎么获取

### ISSUE THREAD

**Issue by bysbol1** [liuxiaoyucc/jd-helper#15]
小白提问如何获取好友的sharecode

**Comment by liuxiaoyucc** [comment]
只能获取自己的哟, 好友的shareCode需要好友提供给你

**Comment by bysbol1** [comment]
> 只能获取自己的哟, 好友的shareCode需要好友提供给你

那自己的要怎么获取呀

**Comment by liuxiaoyucc** [comment]
自己的shareCode是在初始化农场或者宠物时返回的, 在执行脚本时我把shareCode打印在控制台了, 你可以执行下, 然后保存下来, shareCode目前看是不会变化的
![image](https://user-images.githubusercontent.com/33248133/85351545-9f147180-b536-11ea-9d8b-fcab1852437b.png)
![image](https://user-images.githubusercontent.com/33248133/85351563-ad628d80-b536-11ea-9edc-a2061f4fbf7d.png)

**Comment by bysbol1** [comment]
> 自己的shareCode是在初始化农场或者宠物时返回的, 在执行脚本时我把shareCode打印在控制台了, 你可以执行下, 然后保存下来, shareCode目前看是不会变化的
> ![image](https://user-images.githubusercontent.com/33248133/85351545-9f147180-b536-11ea-9d8b-fcab1852437b.png)
> ![image](https://user-images.githubusercontent.com/33248133/85351563-ad628d80-b536-11ea-9edc-a2061f4fbf7d.png)

ok
