### ISSUE TITLE
请问大佬，我该怎么把它放到我的服务器上让他自动运行啊，谢谢大佬

### ISSUE THREAD

**Issue by yongjie9** [liuxiaoyucc/jd-helper#2]

**Comment by liuxiaoyucc** [comment]
恩, 放在服务端的话, 你需要使用一门服务端语言, 比如python, php, java, 携带你账号的cookie, 发起http请求
cookie可以通过分析chrome控制台的network部分获取, 或者抓包, 但是这种cookie不知什么时候会过期, 登录过期需要重新修改cookie
还可以通过分析JD的登录接口, 使用服务器模拟登录动态更新cookie

**Comment by yongjie9** [comment]
谢谢大佬
