### ISSUE TITLE
【问题反馈】今天（6/24）更新代码后出现了新的错误

### ISSUE THREAD

**Issue by igangx** [liuxiaoyucc/jd-helper#20]
如图
![Annotation 2020-06-24 142628](https://user-images.githubusercontent.com/60888291/85508463-b16dd880-b626-11ea-82c1-43bbaac5a693.jpg)

**Comment by liuxiaoyucc** [comment]
我试着修复了下, 之前只写了这块的逻辑, 但是没有测试, 你可以再试下
