### ISSUE TITLE
为什么我的用不了

### ISSUE THREAD

**Issue by little-cabbage1994** [liuxiaoyucc/jd-helper#24]
![image](https://user-images.githubusercontent.com/66833403/89122323-de9c8900-d4f8-11ea-80da-b8e4053e3229.png)
![image](https://user-images.githubusercontent.com/66833403/89122335-ee1bd200-d4f8-11ea-839a-facce2f45771.png)

以前可以的，换了可以设定投喂次数的代码就不可以了（我是小白orz

**Comment by liuxiaoyucc** [comment]
刷新一下页面，把let换成var

**Comment by little-cabbage1994** [comment]
刷新完就可以啦谢谢
