### ISSUE TITLE
狗粮不足时仍然反复投食

### ISSUE THREAD

**Issue by igangx** [liuxiaoyucc/jd-helper#6]
![無題](https://user-images.githubusercontent.com/60888291/84340428-473f4780-abd3-11ea-89ff-5987bda2e30d.png)

**Comment by liuxiaoyucc** [comment]
:stuck_out_tongue_closed_eyes: 疏忽啦, 我加了个提示上去, 然后直接结束投食

**Comment by igangx** [comment]
> 😝 疏忽啦, 我加了个提示上去, 然后直接结束投食

可以了！！Very nice！！

**Comment by igangx** [comment]
不对啊，运行的结果反馈是成功了，可到app一看，好像都没有成功呢。。。

**Comment by liuxiaoyucc** [comment]
> 不对啊，运行的结果反馈是成功了，可到app一看，好像都没有成功呢。。。

你把运行日志截图, 和app中的任务列表截图 贴上来看下, 还有你浏览器登录的账号和app是同一个不

**Comment by igangx** [comment]
> > 不对啊，运行的结果反馈是成功了，可到app一看，好像都没有成功呢。。。
> 
> 你把运行日志截图, 和app中的任务列表截图 贴上来看下, 还有你浏览器登录的账号和app是同一个不

不好意思，是我搞错了，可以正常运行！
