### ISSUE TITLE
农场的广告浏览任务应该不行了

### ISSUE THREAD

**Issue by uniqueque** [liuxiaoyucc/jd-helper#7]
广告浏览任务结果:   {"code":"6","todayGotWaterGoalTask":{"canPop":false},"statisticsTimes":null,"sysTime":1591925475696,"message":null}
不能直接完成了，应该要先去浏览吧

**Comment by liuxiaoyucc** [comment]
我刚试了一下, 我这里还是正常的, 可以直接完成  你用京东微信小程序或者京东app去农场看下, 有没有什么异常

![image](https://user-images.githubusercontent.com/33248133/84457959-7c609e00-ac96-11ea-8a34-8cc8721c09cc.png)

**Comment by uniqueque** [comment]
用浏览器确实可以，我使用quantumultx去执行的，可能少点head
