### ISSUE TITLE
能定时领水滴吗？多个京东账号如何处理？

### ISSUE THREAD

**Issue by lxk0301** [liuxiaoyucc/jd-helper#8]
好像不能领取定时的水滴，有两个京东的cookie， 只做了一个账号的任务

**Comment by liuxiaoyucc** [comment]
两个京东账号, 需要一个一个执行, 先登录一个账号, 执行脚本, 然后退出再登录另一个账号,再执行一遍

定时领水滴, 用浏览器不方便实现, 我自己把定时领水滴的任务放在服务器上, 用cron每天定时跑了
![image](https://user-images.githubusercontent.com/33248133/84490456-c6b53f80-acd5-11ea-8086-99e6db071419.png)

**Comment by lxk0301** [comment]
> 两个京东账号, 需要一个一个执行, 先登录一个账号, 执行脚本, 然后退出再登录另一个账号,再执行一遍
> 
> 定时领水滴, 用浏览器不方便实现, 我自己把定时领水滴的任务放在服务器上, 用cron每天定时跑了
> ![image](https://user-images.githubusercontent.com/33248133/84490456-c6b53f80-acd5-11ea-8086-99e6db071419.png)

我用的是圈x.能否实现定时领水滴呢？里面有cron定时器

**Comment by liuxiaoyucc** [comment]
没用过圈x, 不太了解,  但是如果有cron的话, 然后可以发送http请求, 把你账号的cookie带上, 应该就可以实现的, 三餐的functionID是getThreeMealReward

**Comment by lxk0301** [comment]
好，我自己改改。不过东东萌宠运行完后，我去手机查看，还有200g的食物没投，
![image](https://user-images.githubusercontent.com/21308593/84492236-78557000-acd8-11ea-9464-b2b8d2e0f9f3.png)

![image](https://user-images.githubusercontent.com/21308593/84492162-552ac080-acd8-11ea-9a04-88f280c6bd58.png)

**Comment by liuxiaoyucc** [comment]
脚本里面是执行投食10次的，刚好够完成那个每天投食10次的任务，如果全投了，第二天可能就完不成这个任务了

**Comment by lxk0301** [comment]
> 脚本里面是执行投食10次的，刚好够完成那个每天投食10次的任务，如果全投了，第二天可能就完不成这个任务了

懂了， 多谢！

**Comment by lxk0301** [comment]
@liuxiaoyucc  请问三餐签到 是用到哪个方法,我这边没找到.

**Comment by uniqueque** [comment]
> @liuxiaoyucc 请问三餐签到 是用到哪个方法,我这边没找到.

gotThreeMealForFarm

**Comment by lxk0301** [comment]
@uniqueque 多谢. 水果三餐签到已经完成.
我想添加一下好友助力功能,不知道好友助力的functionId 是多少呢?
东东萌宠那边是slaveHelp. 我在水果这边测试不行.

**Comment by uniqueque** [comment]
> @uniqueque 多谢. 水果三餐签到已经完成.
> 我想添加一下好友助力功能,不知道好友助力的functionId 是多少呢?
> 东东萌宠那边是slaveHelp. 我在水果这边测试不行.

也是initForFarm，body加上shareCode

**Comment by lero007** [comment]
> 两个京东账号, 需要一个一个执行, 先登录一个账号, 执行脚本, 然后退出再登录另一个账号,再执行一遍
> 
> 定时领水滴, 用浏览器不方便实现, 我自己把定时领水滴的任务放在服务器上, 用cron每天定时跑了
> ![image](https://user-images.githubusercontent.com/33248133/84490456-c6b53f80-acd5-11ea-8086-99e6db071419.png)

服务器端怎么设置的，能分享一下具体做法不？
